#!/bin/bash
# tests/unit/test-mod-md-adapter.sh
# v0.1.5: adapter generated by cb_mod_md_adapter_body() must:
#   1. dispatch into /etc/certberus/hooks/<event>.d/
#   2. validate EVENT against a whitelist (path-traversal defense)
#   3. reject invalid DOMAIN (shell injection defense)
#   4. on renewed/installed automatically call 'apache2ctl graceful'
#      Without this Apache does not serve the cert after the first mod_md
#      issuance until a manual reload (real-world bug from example.com).
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/../lib/assert.sh"
source "$HERE/../lib/env.sh"

t_stub_log_helpers
CB_HOOKS_DIR=/tmp/_unused_for_static_analysis
# shellcheck disable=SC1091
source "$CB_REPO_ROOT/lib/hooks.sh"

ADAPTER_TEXT="$(cb_mod_md_adapter_body)"
t_info "adapter content: $(echo "$ADAPTER_TEXT" | wc -l) lines"

# --- Static analysis ---
assert_match "$ADAPTER_TEXT" '^#!/bin/bash' "shebang"
assert_contains "$ADAPTER_TEXT" 'set -u' "set -u (strict)"
assert_contains "$ADAPTER_TEXT" 'HOOKS_DIR="/etc/certberus/hooks"' "HOOKS_DIR const"
assert_contains "$ADAPTER_TEXT" '${EVENT}.d' "dispatch <event>.d"
assert_contains "$ADAPTER_TEXT" 'run-parts' "run-parts cesta"

# Whitelist
assert_contains "$ADAPTER_TEXT" 'pre-issue|post-issue' "whitelist: pre/post-issue"
assert_contains "$ADAPTER_TEXT" 'renewing|renewed|installed' "whitelist: mod_md events"
assert_contains "$ADAPTER_TEXT" 'rejected unknown event' "logger on unknown event"

# CA_* exports
for v in CA_EVENT CA_WEBSERVER CA_PRIMARY_DOMAIN CA_DOMAIN_LIST CA_SOURCE; do
    assert_contains "$ADAPTER_TEXT" "export $v" "export $v"
done

# v0.1.5 fix: auto-graceful reload for Apache
assert_contains "$ADAPTER_TEXT" 'renewed|installed)' "case renewed|installed"
assert_contains "$ADAPTER_TEXT" 'apache2ctl' "calls apache2ctl"
assert_contains "$ADAPTER_TEXT" 'graceful' "graceful"
assert_contains "$ADAPTER_TEXT" 'CB_MOD_MD_AUTO_RELOAD' "respects CB_MOD_MD_AUTO_RELOAD"
assert_contains "$ADAPTER_TEXT" 'CB_HOOK_TIMEOUT' "respects CB_HOOK_TIMEOUT"

# --- Behavioral tests in sandbox ---
SANDBOX="$(t_mktempdir mod-md-adapter)" || exit 1
trap 't_cleanup' EXIT

ADAPTER_SH="$SANDBOX/adapter.sh"
echo "$ADAPTER_TEXT" > "$ADAPTER_SH"

# Patch hardcoded paths to sandbox (otherwise we would write to /etc, /var/log)
sed -i "s|HOOKS_DIR=\"/etc/certberus/hooks\"|HOOKS_DIR=\"$SANDBOX/hooks\"|" "$ADAPTER_SH"
sed -i "s|LOG=\"/var/log/certberus/mod_md-events.log\"|LOG=\"$SANDBOX/events.log\"|" "$ADAPTER_SH"
chmod +x "$ADAPTER_SH"

if bash -n "$ADAPTER_SH" 2>"$SANDBOX/syn.err"; then
    t_pass "adapter has valid bash syntax"
else
    t_fail "adapter syntax" "$(cat "$SANDBOX/syn.err")"
fi

# Helper: creates a marker hook in event.d/. Adapter should execute it at runtime.
make_hook() {
    local event="$1"
    mkdir -p "$SANDBOX/hooks/${event}.d"
    cat > "$SANDBOX/hooks/${event}.d/10-marker.sh" <<EOF
#!/bin/bash
echo "FIRED:\$CA_EVENT:\$CA_PRIMARY_DOMAIN" > "$SANDBOX/marker"
EOF
    chmod +x "$SANDBOX/hooks/${event}.d/10-marker.sh"
}

# A) Path-traversal in EVENT
make_hook "renewed"
rm -f "$SANDBOX/marker"
CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "../../etc/passwd" "x.example.com" >/dev/null 2>&1 || true
[[ ! -f "$SANDBOX/marker" ]] && t_pass "EVENT whitelist blocks path-traversal" \
    || t_fail "EVENT whitelist bypassed" "marker: $(cat "$SANDBOX/marker")"

# B) Shell injection in DOMAIN
rm -f "$SANDBOX/marker"
CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "renewed" "evil; rm -rf /" >/dev/null 2>&1 || true
[[ ! -f "$SANDBOX/marker" ]] && t_pass "DOMAIN regex blocks shell metacharacters" \
    || t_fail "DOMAIN regex bypassed"

# C) Valid renewed/example.com - hook MUST execute
rm -f "$SANDBOX/marker"
CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "renewed" "example.com" >/dev/null 2>&1 || true
if [[ -f "$SANDBOX/marker" ]]; then
    assert_eq "FIRED:renewed:example.com" "$(cat "$SANDBOX/marker")" \
        "hook executed with CA_EVENT=renewed, CA_PRIMARY_DOMAIN=example.com"
else
    # Some CI runtimes have /tmp noexec - test with bash invocation as well
    rm -f "$SANDBOX/marker"
    bash "$SANDBOX/hooks/renewed.d/10-marker.sh" </dev/null
    if [[ -f "$SANDBOX/marker" ]]; then
        t_skip "run-parts did not execute hook (possibly noexec mount); hook itself works"
    else
        t_fail "hook did not run even manually" "ls: $(ls -la "$SANDBOX/hooks/renewed.d/" 2>&1)"
    fi
fi

# D) Wildcard *.example.com is valid
rm -f "$SANDBOX/marker"
make_hook "installed"
CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "installed" "*.example.com" >/dev/null 2>&1 || true
if [[ -f "$SANDBOX/marker" ]]; then
    t_pass "wildcard '*.example.com' accepted"
else
    # noexec fallback - at least verify that the adapter did not exit with reject
    err=$(CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "installed" "*.example.com" 2>&1 >/dev/null || true)
    if [[ "$err" != *"rejected"* ]]; then
        t_skip "wildcard accepted (run-parts not executed due to mount); regex passes"
    else
        t_fail "wildcard '*.example.com' unexpectedly rejected"
    fi
fi

# E) Empty DOMAIN (mod_md challenge-setup)
rm -f "$SANDBOX/marker"
make_hook "challenge-setup"
out=$(CB_MOD_MD_AUTO_RELOAD=0 bash "$ADAPTER_SH" "challenge-setup" "" 2>&1 >/dev/null || true)
[[ "$out" != *"rejected"* ]] && t_pass "empty DOMAIN accepted" || t_fail "empty DOMAIN rejected"

# F) CB_MOD_MD_AUTO_RELOAD=0 MUST NOT call apache2ctl
APCH_TRACE="$SANDBOX/apache2ctl-called"
mkdir -p "$SANDBOX/fakebin"
cat > "$SANDBOX/fakebin/apache2ctl" <<EOF
#!/bin/bash
echo "called:\$*" > "$APCH_TRACE"
EOF
chmod +x "$SANDBOX/fakebin/apache2ctl"
# Adapter looks for apache2ctl in /usr/sbin etc. - patch it to our fake
PATCHED="$SANDBOX/adapter-fakeapcr.sh"
sed "s|/usr/sbin/apache2ctl|$SANDBOX/fakebin/apache2ctl|g; s|/usr/sbin/apachectl|/nonexistent|g; s|/usr/local/sbin/apache2ctl|/nonexistent|g" "$ADAPTER_SH" > "$PATCHED"
chmod +x "$PATCHED"

rm -f "$APCH_TRACE"
CB_MOD_MD_AUTO_RELOAD=0 bash "$PATCHED" "renewed" "example.com" >/dev/null 2>&1 || true
[[ ! -f "$APCH_TRACE" ]] && t_pass "CB_MOD_MD_AUTO_RELOAD=0 does NOT call apache2ctl" \
    || t_fail "CB_MOD_MD_AUTO_RELOAD=0 called apache2ctl" "$(cat "$APCH_TRACE")"

# G) CB_MOD_MD_AUTO_RELOAD=1 (default) MUST call apache2ctl graceful on renewed
rm -f "$APCH_TRACE"
CB_MOD_MD_AUTO_RELOAD=1 bash "$PATCHED" "renewed" "example.com" >/dev/null 2>&1 || true
if [[ -f "$APCH_TRACE" ]]; then
    assert_contains "$(cat "$APCH_TRACE")" "graceful" "default calls 'apache2ctl graceful'"
else
    t_fail "default ${CB_MOD_MD_AUTO_RELOAD:-1} did not call apache2ctl on renewed (regression)"
fi

# H) Apache reload MUST NOT be called on pre-issue/post-issue (only renewed/installed)
rm -f "$APCH_TRACE"
CB_MOD_MD_AUTO_RELOAD=1 bash "$PATCHED" "post-issue" "example.com" >/dev/null 2>&1 || true
[[ ! -f "$APCH_TRACE" ]] && t_pass "post-issue did NOT call apache2ctl (only renewed/installed)" \
    || t_fail "post-issue called apache2ctl" "should not have"

t_summary
